name: Create Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: >
          The version that is being created, in the format of <year>.<major>.<minor>
          (for example, 2025.2, or 2025.2.3)
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Create New Version Branch
        id: create-version-branch
        run: |
          VERSION_BRANCH_NAME="versions/${{ github.event.inputs.version }}"
          echo "version-branch-name=$VERSION_BRANCH_NAME" >> $GITHUB_OUTPUT
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout -b "$VERSION_BRANCH_NAME"

      - name: Push New Version Branch
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ steps.create-version-branch.outputs.version-branch-name }}
          github_token: ${{ secrets.ACTIONS_TOKEN }}
