name: Create Build

on:
  create:
  pull_request:
    branches:
      - versions/**
  push:
    branches:
      - versions/**
  workflow_call:
    inputs:
      version:
        description: The version from which to create the builds/** branch.
        required: true
        type: string

jobs:
  create-build:
    if: |
      (github.event_name == 'create' && github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/versions/'))
      || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      || (github.event_name == 'push')
      || (github.event_name == 'workflow_call')
    runs-on: ubuntu-latest
    steps:
      - name: Compute Version
        id: compute-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else        
            echo "version=${GITHUB_REF#refs/heads/versions/}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout versions/** Branch
        uses: actions/checkout@v4
        with:
          ref: versions/${{ steps.compute-version.outputs.version }}

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Angular Project
        working-directory: client
        run: npm install && npm run build:prod

      - name: Deploy to Build Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds/${{ steps.compute-version.outputs.version }}
          folder: client/dist/browser
          token: ${{ secrets.ACTIONS_TOKEN }}
