name: Create Build

on:
  create:
    branches:
      - versions/**
  push:
    branches:
      - versions/**

jobs:
  create-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build
        working-directory: client
        run: npm install && npm run build:prod

      - name: Compute Build Branch Name
        id: compute-build-branch-name
        run: echo "build-branch-name=builds${GITHUB_REF#refs/heads/versions}" >> $GITHUB_OUTPUT

      - name: Deploy to Build Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ steps.compute-build-branch-name.outputs.build-branch-name }}
          folder: client/dist/browser
          token: ${{ secrets.ACTIONS_TOKEN }}
