name: Cut Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: >
          The version that is being cut, in the format of <year>.<major>
          (for example, 2025.2). New minor versions should not be cut.
        type: string
        required: true

jobs:
  cut-version:
    runs-on: ubuntu-latest
    outputs:
      branch-created: ${{ steps.create-branch.outputs.branch-created }}
    steps:
      - name: Checkout main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create New versions/** Branch
        id: create-branch
        run: |
          BRANCH_NAME="versions/${{ inputs.version }}"
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            echo "branch-created=false" >> $GITHUB_OUTPUT
          else
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git checkout -b "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"
            echo "branch-created=true" >> $GITHUB_OUTPUT
          fi

  create-build:
    needs: cut-version
    if: ${{ needs.cut-version.outputs.branch-created }}
    uses: ./.github/workflows/create-build.yaml
    with:
      version: ${{ inputs.version }}
