name: Test Flow

on:
  workflow_call:
    inputs:
      testinput:
        description: The version from which to create the builds/** branch.
        type: string
        required: true
    secrets:
      ACTIONS_TOKEN:
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Compute Version
        id: compute-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "version=${{ inputs.testinput }}" >> $GITHUB_OUTPUT
            echo "good"
          else        
            echo "bad"
          fi
