name: Test Flow

on:
  workflow_call:
    inputs:
      testinput:
        description: The version from which to create the builds/** branch.
        type: string
        required: true
    secrets:
      ACTIONS_TOKEN:
        required: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Compute Version
        run: echo "hello${{ inputs.testinput }}"
